services:
    # React container image, used as our frontend application
    react:
        build: ./frontend
        container_name: react
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - node_modules:/app/node_modules

    # Backend application built in django
    django:
        build: ./backend
        container_name: django
        env_file:
            - .env
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app
        depends_on:
            - postgres

    # Our Postgres database
    postgres:
        image: postgres:13
        container_name: postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    celery:
        build: ./backend
        container_name: celery
        command: celery -A core worker --loglevel=info
        volumes:
            - ./backend:/app
        env_file:
            - .env
        depends_on:
            - django
            - rabbitmq
            - postgres

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        environment:
          RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
          RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-admin}
        ports:
          - "5672:5672"
          - "15672:15672"
        volumes:
          - rabbitmq_data:/var/lib/rabbitmq

volumes:
    node_modules:
    postgres_data:
    rabbitmq_data: